services:
  jupyterlab: 
    image: problem5
    env_file:
      - .env
    ports: 
      - "8888:8888"
    volumes: 
      - ./:/problem5
    networks:
      - dbnetwork
  postgres:
    image: postgres:latest
    env_file: 
      - .env 
    ports: 
      - "5432:5432"
    volumes:
      - postgresdata:/var/lib/postgresql/data
    networks:
      - dbnetwork
volumes:
  postgresdata:
networks:
  dbnetwork: